let arr = [
    {
      id: 4,
      parentId: 0,
      title: "首页",
      icon: null,
      path: "/",
      permission: null,
      type: 1,
      sort: 0,
      status: 1,
      source: 2,
      description: null,
      component: null,
      children: [],
      language: {},
    },
    {
      id: 5,
      parentId: 0,
      title: "系统设置",
      icon: "el-icon-monitor",
      path: "/system",
      permission: null,
      type: 1,
      sort: 1,
      status: 1,
      source: 1,
      description: null,
      component: null,
      children: [
        {
          id: 11,
          parentId: 5,
          title: "菜单管理",
          icon: null,
          path: "menu",
          permission: null,
          type: 1,
          sort: 1,
          status: 1,
          source: 0,
          description: null,
          component: null,
          children: [],
          language: {},
        },
        {
          id: 12,
          parentId: 5,
          title: "角色管理",
          icon: null,
          path: "role",
          permission: null,
          type: 1,
          sort: 1,
          status: 1,
          source: 0,
          description: null,
          component: null,
          children: [],
          language: {},
        },
      ],
      language: {},
    },
    {
      id: 6,
      parentId: 0,
      title: "大屏展示",
      icon: "el-icon-monitor",
      path: null,
      permission: "1",
      type: 1,
      sort: 2,
      status: 1,
      source: 0,
      description: null,
      component: null,
      children: [],
      language: {},
    },
    {
      id: 7,
      parentId: 0,
      title: "搜索选择",
      icon: "",
      path: null,
      permission: null,
      type: 3,
      sort: 10,
      status: 1,
      source: 0,
      description: "1",
      component: null,
      children: [
        {
          id: 2,
          parentId: 7,
          title: "北理工wiki",
          icon: null,
          path: "https://byaerocloud.coding.net/p/BitUTS/wiki/11",
          permission: null,
          type: 3,
          sort: 9,
          status: 1,
          source: 0,
          description: null,
          component: null,
          children: [],
          language: {},
        },
        {
          id: 8,
          parentId: 7,
          title: "百度",
          icon: "",
          path: "https://www.baidu.com/",
          permission: null,
          type: 1,
          sort: 10,
          status: 1,
          source: 0,
          description: "外部链接",
          component: null,
          children: [
            {
              id: 1,
              parentId: 8,
              title: "百度搜索",
              icon: "",
              path: "https://www.baidu.com/",
              permission: "forward_baidu:to",
              type: 3,
              sort: 10,
              status: 1,
              source: 0,
              description: "123",
              component: null,
              children: [],
              language: {},
            },
            {
              id: 3,
              parentId: 8,
              title: "element",
              icon: null,
              path: "https://element.eleme.cn/#/zh-CN/component/layout",
              permission: null,
              type: 3,
              sort: 9,
              status: 1,
              source: 1,
              description: null,
              component: null,
              children: [],
              language: {},
            },
          ],
          language: {},
        },
      ],
      language: {},
    },
    {
      id: 9,
      parentId: 0,
      title: "菜单管理",
      icon: null,
      path: null,
      permission: null,
      type: 1,
      sort: 1,
      status: 1,
      source: 0,
      description: "暂无配置",
      component: null,
      children: [],
      language: {},
    },
    {
      id: 10,
      parentId: 0,
      title: "菜单管理",
      icon: null,
      path: null,
      permission: null,
      type: 1,
      sort: 1,
      status: 1,
      source: 0,
      description: "暂无配置\n",
      component: null,
      children: [],
      language: {},
    },
  ];

  const routerMap = {
    menu: () => import('@/views/system/menu/index'),
    role: () => import('@/views/system/role/index'),
    first: () => import('@/views/dashboard/index'),
    layout: "Layout"
}